Add Server-Sent Events
EarthMC/EMCAPI pull request #16
Opened 2024-08-26 23:33 UTC by mrtoirol

This PR adds a `/events` endpoint to the API that users can use as an [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource). This endpoint relays and broadcasts multiple Towny events in real time, using server-sent events (SSE) through Javalin. The complete list and data structure can be found in the docs.

2025-01-19 14:50 UTC, Warriorrrr requested changes

2025-01-19 14:50 UTC, Warriorrrr commented on src/main/java/net/earthmc/emcapi/manager/SSEManager.java
> +        );
This can be simplified, the result of the futures is ignored so combining them into one is redundant.

(requires adding a plugin field obviously)
```suggestion
        for (final SseClient client : clients) {
        	plugin.getServer().getAsyncScheduler().runNow(plugin, task -> client.sendEvent(event, message));
        }
```

2025-01-19 14:50 UTC, Warriorrrr commented on src/main/java/net/earthmc/emcapi/listeners/PlayerConnectionListener.java
> +public class PlayerConnectionListener implements Listener {
I think that player join/quit events are too intrusive, this class should be removed

2025-01-21 23:04 UTC, wyattgill9 commented on src/main/java/net/earthmc/emcapi/listeners/PlayerConnectionListener.java
> +public class PlayerConnectionListener implements Listener {
I shadow Warriorrrr's opinion, those events are intrusive though, it can prove helpful to have it...

2025-01-25 06:46 UTC, Owen3H commented
Imo, the event names could cause some confusion, for example "DeleteNation" sounds like the event deletes the nation.
Instead I think they could be a bit more consistent and convey what happened a bit better.

`RenameTown` -> `TownRenamed`
`DeleteTown` -> `TownDeleted`
`NewTown` -> `TownCreated`

`RenameNation` -> `NationRenamed`
`DeleteNation` -> `NationDeleted`
`NewNation` -> `NationCreated`
`NationRemoveTown` -> `NationTownRemoved`
`NationAddTown` -> `NationTownAdded`

2025-12-05 10:18 UTC, closed without merging